"""empty message

Revision ID: 18788f32b02d
Revises: 82e892733967
Create Date: 2024-10-03 04:09:34.948142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18788f32b02d'
down_revision = '82e892733967'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mensajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_coach', sa.Integer(), nullable=True),
    sa.Column('contenido', sa.String(), nullable=False),
    sa.Column('fecha_envio', sa.DateTime(), nullable=True),
    sa.Column('visto', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_coach'], ['coach.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['smoker_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seguimiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.String(length=120), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_tipo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_tipo'], ['tipos_consumo.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['smoker_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seguimiento')
    op.drop_table('mensajes')
    # ### end Alembic commands ###
