"""Nueva migración después de eliminar duplicadas

Revision ID: 734a39a73107
Revises: 98233ca609b4
Create Date: 2024-10-07 02:10:38.229288

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '734a39a73107'
down_revision = '98233ca609b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitudes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_coach', sa.Integer(), nullable=True),
    sa.Column('fecha_solicitud', sa.Date(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('fecha_respuesta', sa.Date(), nullable=True),
    sa.Column('comentarios', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_coach'], ['coach.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['smoker_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('solicitud')
    with op.batch_alter_table('coach', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nacimiento_coach', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coach', schema=None) as batch_op:
        batch_op.drop_column('nacimiento_coach')

    op.create_table('solicitud',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_coach', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha_solicitud', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('estado', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('fecha_respuesta', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('comentarios', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_coach'], ['coach.id'], name='solicitud_id_coach_fkey'),
    sa.ForeignKeyConstraint(['id_user'], ['smoker_user.id'], name='solicitud_id_user_fkey'),
    sa.PrimaryKeyConstraint('id', name='solicitud_pkey')
    )
    op.drop_table('solicitudes')
    # ### end Alembic commands ###
