"""empty message

Revision ID: 784b15ba978b
Revises: 9efe72c5a674
Create Date: 2024-09-28 14:23:43.883075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '784b15ba978b'
down_revision = '9efe72c5a674'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipos_consumo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tipos_consumo')
    # ### end Alembic commands ###
