"""empty message

Revision ID: 82e892733967
Revises: 57bef4860a66
Create Date: 2024-09-30 21:45:32.347372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82e892733967'
down_revision = '57bef4860a66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('smoker_user', schema=None) as batch_op:
        batch_op.alter_column('nombre_usuario',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('genero_usuario',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('nacimiento_usuario',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('numerocigarro_usuario',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('periodicidad',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('tiempo_fumando',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('id_tipo',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('smoker_user', schema=None) as batch_op:
        batch_op.alter_column('id_tipo',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('tiempo_fumando',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('periodicidad',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('numerocigarro_usuario',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('nacimiento_usuario',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('genero_usuario',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('nombre_usuario',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)

    # ### end Alembic commands ###
