"""empty message

Revision ID: 9efe72c5a674
Revises: 420ea18aabef
Create Date: 2024-09-27 23:52:01.726897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9efe72c5a674'
down_revision = '420ea18aabef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smoker_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_usuario', sa.String(length=120), nullable=False),
    sa.Column('password_email', sa.String(length=80), nullable=False),
    sa.Column('nombre_usuario', sa.String(length=80), nullable=False),
    sa.Column('genero_usuario', sa.String(length=10), nullable=False),
    sa.Column('nacimiento_usuario', sa.Date(), nullable=False),
    sa.Column('numerocigarro_usuario', sa.Integer(), nullable=False),
    sa.Column('periodicidad', sa.String(length=50), nullable=False),
    sa.Column('tiempo_fumando', sa.String(length=10), nullable=False),
    sa.Column('id_tipo', sa.Integer(), nullable=False),
    sa.Column('foto_usuario', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_usuario')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('smoker_user')
    # ### end Alembic commands ###
