"""empty message

Revision ID: afee3739f821
Revises: 784b15ba978b
Create Date: 2024-09-29 18:36:20.801005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afee3739f821'
down_revision = '784b15ba978b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coach',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_coach', sa.String(length=120), nullable=False),
    sa.Column('password_coach', sa.String(length=128), nullable=False),
    sa.Column('nombre_coach', sa.String(length=50), nullable=False),
    sa.Column('genero_coach', sa.String(length=10), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('descripcion_coach', sa.Text(), nullable=True),
    sa.Column('foto_coach', sa.String(length=200), nullable=True),
    sa.Column('precio_servicio', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_coach')
    )
    with op.batch_alter_table('smoker_user', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'tipos_consumo', ['id_tipo'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('smoker_user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('coach')
    # ### end Alembic commands ###
