"""empty message

Revision ID: dcfd8298e879
Revises: 734a39a73107
Create Date: 2024-10-10 12:07:53.711392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcfd8298e879'
down_revision = '734a39a73107'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mensajes_ocultos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_mensaje', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_mensaje'], ['mensajes.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['smoker_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mensajes_ocultos')
    # ### end Alembic commands ###
