"""empty message

Revision ID: f3e0b5500cfb
Revises: 18788f32b02d
Create Date: 2024-10-03 09:33:43.085217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3e0b5500cfb'
down_revision = '18788f32b02d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitud',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_coach', sa.Integer(), nullable=True),
    sa.Column('fecha_solicitud', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('fecha_respuesta', sa.DateTime(), nullable=True),
    sa.Column('comentarios', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_coach'], ['coach.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['smoker_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coach', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_id', sa.String(length=200), nullable=True))

    with op.batch_alter_table('smoker_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_id', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('smoker_user', schema=None) as batch_op:
        batch_op.drop_column('public_id')

    with op.batch_alter_table('coach', schema=None) as batch_op:
        batch_op.drop_column('public_id')

    op.drop_table('solicitud')
    # ### end Alembic commands ###
